import type { Metadata } from 'next';
import './globals.css';

import { RecaptchaProvider } from '@/components/recaptch-provider';
import { Golos_Text, Manrope } from 'next/font/google';

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-manrope',
  weight: ['400', '500', '600', '700', '800'],
});

const golos = Golos_Text({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-golos',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${manrope.variable} ${golos.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <RecaptchaProvider>{children}</RecaptchaProvider>
      </body>
    </html>
  );
}
