export type Review = {
  id: number;
  author: string;
  avatar: string;
  rating: number;
  date: string;
  text: string;
  helpful: number;
  verified: boolean;
};

export type ProductImage = {
  id: number;
  url: string;
  alt: string;
  color?: string;
};

export type ProductSpec = {
  label: string;
  value: string;
};

export type Product = {
  id: number;
  slug: string;
  name: string;
  brand: string;
  category: string;
  subcategory: string;
  price: number;
  originalPrice: number;
  discount: number;
  currency: string;
  rating: number;
  reviewsCount: number;
  soldCount: number;
  inStock: boolean;
  stockLeft?: number;
  isNew: boolean;
  isFeatured: boolean;
  isExpress: boolean;
  badge?: string;
  shortDescription: string;
  description: string;
  images: ProductImage[];
  colors: string[];
  sizes?: string[];
  specs: ProductSpec[];
  reviews: Review[];
  tags: string[];
  deliveryDays: number;
  warranty?: string;
};

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'samsung-galaxy-s24-ultra',
    name: 'Samsung Galaxy S24 Ultra',
    brand: 'Samsung',
    category: 'Электроника',
    subcategory: 'Смартфоны',
    price: 89990,
    originalPrice: 109990,
    discount: 18,
    currency: 'сом',
    rating: 4.8,
    reviewsCount: 342,
    soldCount: 1204,
    inStock: true,
    stockLeft: 8,
    isNew: false,
    isFeatured: true,
    isExpress: true,
    badge: 'Хит продаж',
    shortDescription:
      'Флагманский смартфон с встроенным S Pen, камерой 200 МП и процессором Snapdragon 8 Gen 3.',
    description: `Samsung Galaxy S24 Ultra — вершина мобильных технологий 2024 года. Оснащён встроенным стилусом S Pen с нулевой задержкой, что делает его идеальным для художников и деловых людей. Камера 200 МП с оптическим зумом 10x позволяет снимать детали на расстоянии до 100 метров. Процессор Snapdragon 8 Gen 3 обеспечивает молниеносную работу AI-функций: мгновенный перевод речи, умный поиск на фото и Circle to Search. Аккумулятор 5000 мАч с быстрой зарядкой 45W держит до двух дней без подзарядки. Корпус из титана Armor и стекло Gorilla Glass Armor делают телефон одним из самых прочных на рынке.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
        alt: 'Samsung Galaxy S24 Ultra — чёрный',
        color: '#1a1a1a',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1610945415295-d9b226b44000?w=600&auto=format&fit=crop&q=80',
        alt: 'Samsung Galaxy S24 Ultra — камера',
        color: '#1a1a1a',
      },
      {
        id: 3,
        url: 'https://images.unsplash.com/photo-1565630916779-e303be97b6f5?w=600&auto=format&fit=crop&q=80',
        alt: 'Samsung Galaxy S24 Ultra — бок',
        color: '#C0C0C0',
      },
    ],
    colors: ['Титановый чёрный', 'Титановый серый', 'Фиолетовый'],
    specs: [
      { label: 'Дисплей', value: '6.8" Dynamic AMOLED 2X, 120 Гц' },
      { label: 'Процессор', value: 'Snapdragon 8 Gen 3' },
      { label: 'Камера', value: '200 МП + 12 МП + 10 МП + 50 МП' },
      { label: 'Аккумулятор', value: '5000 мАч, 45W зарядка' },
      { label: 'Память', value: '12 ГБ / 256 ГБ' },
      { label: 'ОС', value: 'Android 14, One UI 6.1' },
      { label: 'Защита', value: 'IP68' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Айдана К.',
        avatar: 'АК',
        rating: 5,
        date: '12 марта 2025',
        text: 'Лучший телефон, который у меня был! S Pen очень удобен для работы, камера снимает потрясающе даже ночью. Батарея держит весь день даже при активном использовании.',
        helpful: 47,
        verified: true,
      },
      {
        id: 2,
        author: 'Бекзат М.',
        avatar: 'БМ',
        rating: 5,
        date: '5 февраля 2025',
        text: 'Перешёл с iPhone 15 Pro — не пожалел. Экран ярче, камера лучше, а S Pen открывает возможности которых раньше не было. Zoom 10x — это что-то невероятное.',
        helpful: 31,
        verified: true,
      },
      {
        id: 3,
        author: 'Гульнара Т.',
        avatar: 'ГТ',
        rating: 4,
        date: '20 января 2025',
        text: 'Отличный телефон, но очень большой — в руке не очень удобно держать. Камера супер, скорость работы тоже. Минус — нагревается при долгой съёмке видео.',
        helpful: 18,
        verified: false,
      },
    ],
    tags: ['смартфон', 'samsung', 'флагман', 's pen', '5g'],
    deliveryDays: 1,
    warranty: '12 месяцев',
  },

  {
    id: 2,
    slug: 'nike-air-max-270',
    name: 'Nike Air Max 270',
    brand: 'Nike',
    category: 'Одежда и мода',
    subcategory: 'Кроссовки',
    price: 8490,
    originalPrice: 11990,
    discount: 29,
    currency: 'сом',
    rating: 4.6,
    reviewsCount: 218,
    soldCount: 893,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isExpress: true,
    badge: 'Скидка 29%',
    shortDescription:
      'Культовые кроссовки с самой большой воздушной подушкой в истории Nike Air — для стиля и комфорта весь день.',
    description: `Nike Air Max 270 — это культовая модель, которая объединяет уличный стиль и максимальный комфорт. Воздушная подушка Air Max объёмом 270° — самая большая в линейке Nike, обеспечивает непревзойдённую амортизацию при каждом шаге. Верх из дышащего mesh-материала и синтетических накладок создаёт лёгкую и поддерживающую посадку. Подошва из пеноматериала Phylon дополнительно гасит удары. Модель одинаково хорошо подходит для прогулок по городу, лёгких тренировок и повседневной носки. Доступна в множестве цветовых решений.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
        alt: 'Nike Air Max 270 — белые',
        color: '#FFFFFF',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600',
        alt: 'Nike Air Max 270 — подошва',
        color: '#FFFFFF',
      },
      {
        id: 3,
        url: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=600',
        alt: 'Nike Air Max 270 — чёрные',
        color: '#1a1a1a',
      },
    ],
    colors: ['Белый/Чёрный', 'Чёрный/Красный', 'Синий/Серый'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
    specs: [
      { label: 'Верх', value: 'Mesh + синтетика' },
      { label: 'Подошва', value: 'Phylon + Air Max 270°' },
      { label: 'Назначение', value: 'Lifestyle / лёгкий бег' },
      { label: 'Вес', value: '310 г (размер 42)' },
      { label: 'Страна', value: 'Вьетнам' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Эрлан С.',
        avatar: 'ЭС',
        rating: 5,
        date: '8 апреля 2025',
        text: 'Очень удобные! Хожу в них весь день на работе — ноги не устают. Подошва реально амортизирует. Выглядят стильно, получил много комплиментов.',
        helpful: 23,
        verified: true,
      },
      {
        id: 2,
        author: 'Жамиля О.',
        avatar: 'ЖО',
        rating: 4,
        date: '15 марта 2025',
        text: 'Красивые и лёгкие. Размер соответствует, брала 39й. Единственное — белая подошва быстро пачкается, приходится чистить. В целом довольна покупкой.',
        helpful: 12,
        verified: true,
      },
      {
        id: 3,
        author: 'Нурдан А.',
        avatar: 'НА',
        rating: 5,
        date: '2 февраля 2025',
        text: 'Уже третьи Air Max — каждый раз возвращаюсь к этой модели. Качество отличное, носил прошлые пару лет без проблем.',
        helpful: 9,
        verified: false,
      },
    ],
    tags: ['кроссовки', 'nike', 'air max', 'спорт', 'lifestyle'],
    deliveryDays: 2,
    warranty: '30 дней возврат',
  },

  {
    id: 3,
    slug: 'dyson-v15-detect',
    name: 'Dyson V15 Detect Absolute',
    brand: 'Dyson',
    category: 'Дом и сад',
    subcategory: 'Пылесосы',
    price: 54990,
    originalPrice: 64990,
    discount: 15,
    currency: 'сом',
    rating: 4.9,
    reviewsCount: 97,
    soldCount: 312,
    inStock: true,
    stockLeft: 3,
    isNew: false,
    isFeatured: true,
    isExpress: false,
    badge: 'Премиум',
    shortDescription:
      'Беспроводной пылесос с лазерным выявлением пыли и автоматической регулировкой мощности. Самый умный пылесос Dyson.',
    description: `Dyson V15 Detect Absolute — революционный беспроводной пылесос, оснащённый лазерной технологией выявления пыли. Зелёный лазер, встроенный в насадку, подсвечивает мельчайшие частицы пыли, которые невидимы невооружённым глазом. Пьезоэлектрический датчик считает и классифицирует частицы в реальном времени, автоматически регулируя мощность всасывания. Двигатель Hyperdymium вращается со скоростью 125 000 об/мин и создаёт мощность всасывания 240 АВт. HEPA-фильтрация задерживает 99,99% частиц размером до 0,1 мкм. Аккумулятор обеспечивает до 60 минут работы.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
        alt: 'Dyson V15 Detect — общий вид',
        color: '#FFD700',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600',
        alt: 'Dyson V15 — насадки',
        color: '#FFD700',
      },
    ],
    colors: ['Жёлтый/Никель'],
    specs: [
      { label: 'Мощность всасывания', value: '240 АВт' },
      { label: 'Время работы', value: 'До 60 минут' },
      { label: 'Ёмкость контейнера', value: '0.77 л' },
      { label: 'Фильтрация', value: 'HEPA (99,99%)' },
      { label: 'Вес', value: '3.1 кг' },
      { label: 'Зарядка', value: '4.5 часа' },
      { label: 'Уровень шума', value: '73 дБ' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Светлана П.',
        avatar: 'СП',
        rating: 5,
        date: '20 апреля 2025',
        text: 'После обычного пылесоса это как переход с кнопочного телефона на смартфон! Лазер показывает сколько пыли там, где думаешь что чисто — шок. Рекомендую всем!',
        helpful: 64,
        verified: true,
      },
      {
        id: 2,
        author: 'Тимур Ж.',
        avatar: 'ТЖ',
        rating: 5,
        date: '11 марта 2025',
        text: 'Дорого, но того стоит. Жена аллергик — после покупки этого пылесоса симптомы значительно уменьшились. HEPA фильтр реально работает.',
        helpful: 41,
        verified: true,
      },
    ],
    tags: ['пылесос', 'dyson', 'беспроводной', 'hepa', 'умный дом'],
    deliveryDays: 3,
    warranty: '24 месяца',
  },

  {
    id: 4,
    slug: 'apple-airpods-pro-2',
    name: 'Apple AirPods Pro 2-го поколения',
    brand: 'Apple',
    category: 'Электроника',
    subcategory: 'Наушники',
    price: 19990,
    originalPrice: 23990,
    discount: 17,
    currency: 'сом',
    rating: 4.7,
    reviewsCount: 524,
    soldCount: 2341,
    inStock: true,
    isNew: false,
    isFeatured: true,
    isExpress: true,
    badge: 'Бестселлер',
    shortDescription:
      'Беспроводные наушники с активным шумоподавлением H2, персонализированным пространственным звуком и зарядкой через USB-C.',
    description: `Apple AirPods Pro второго поколения устанавливают новый стандарт беспроводных наушников. Чип H2 обеспечивает в 2 раза более эффективное шумоподавление по сравнению с предыдущим поколением. Адаптивный режим прозрачности использует вычислительный звук для управления громкими звуками окружающей среды. Персонализированный пространственный звук с отслеживанием движений головы создаёт кинематографический звуковой опыт. Чехол MagSafe теперь поддерживает зарядку через USB-C и работает как трекер FindMy. До 30 часов работы с чехлом. Новый размер XS силиконовых вкладышей для лучшего прилегания.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1606741965326-cb990ae01bb2?w=600',
        alt: 'AirPods Pro 2 — в чехле',
        color: '#FFFFFF',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600',
        alt: 'AirPods Pro 2 — наушники',
        color: '#FFFFFF',
      },
    ],
    colors: ['Белый'],
    specs: [
      { label: 'Чип', value: 'Apple H2' },
      { label: 'Шумоподавление', value: 'Активное (ANC)' },
      { label: 'Время работы', value: '6 ч + 24 ч с чехлом' },
      { label: 'Зарядка', value: 'USB-C / MagSafe / Watch' },
      { label: 'Защита', value: 'IP54 (наушники + чехол)' },
      { label: 'Связь', value: 'Bluetooth 5.3' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Алина Ф.',
        avatar: 'АФ',
        rating: 5,
        date: '3 мая 2025',
        text: 'Шумоподавление просто фантастическое. В офисе с открытым пространством — полная тишина. Звук очень сбалансированный, бас не перегружен.',
        helpful: 89,
        verified: true,
      },
      {
        id: 2,
        author: 'Дастан Р.',
        avatar: 'ДР',
        rating: 4,
        date: '17 апреля 2025',
        text: 'Отличные наушники для Apple экосистемы. Переключение между устройствами мгновенное. Немного жмут после 3 часов, но вкладыши XS решили проблему.',
        helpful: 34,
        verified: true,
      },
      {
        id: 3,
        author: 'Камила Ш.',
        avatar: 'КШ',
        rating: 5,
        date: '1 апреля 2025',
        text: 'Купила для занятий спортом — не выпадают даже при беге. Звонки в шумном метро — собеседник слышит идеально. Стоят каждого сома.',
        helpful: 21,
        verified: true,
      },
    ],
    tags: ['наушники', 'apple', 'airpods', 'anc', 'беспроводные'],
    deliveryDays: 1,
    warranty: '12 месяцев',
  },

  {
    id: 5,
    slug: 'xiaomi-robot-vacuum-s20',
    name: 'Xiaomi Robot Vacuum S20+',
    brand: 'Xiaomi',
    category: 'Дом и сад',
    subcategory: 'Роботы-пылесосы',
    price: 24990,
    originalPrice: 29990,
    discount: 17,
    currency: 'сом',
    rating: 4.5,
    reviewsCount: 143,
    soldCount: 487,
    inStock: true,
    isNew: true,
    isFeatured: false,
    isExpress: false,
    badge: 'Новинка',
    shortDescription:
      'Умный робот-пылесос с лазерной навигацией LDS, мощностью всасывания 4000 Па и самоочищающейся базой.',
    description: `Xiaomi Robot Vacuum S20+ — умный помощник по дому нового поколения. Лазерная навигация LDS строит точную карту вашего дома и прокладывает оптимальный маршрут уборки. Мощность всасывания 4000 Па справляется с любыми загрязнениями — от мелкой пыли до шерсти животных. Самоочищающаяся база автоматически опустошает контейнер пылесоса — вам нужно очищать мешок только раз в 60 дней. Вибрирующая швабра с давлением 300 г эффективно отмывает засохшие пятна. Управление через приложение Mi Home позволяет задавать расписание, зоны уборки и запретные зоны.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
        alt: 'Xiaomi Robot Vacuum — вид сверху',
        color: '#1a1a1a',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=600',
        alt: 'Xiaomi Robot Vacuum — база',
        color: '#1a1a1a',
      },
    ],
    colors: ['Чёрный'],
    specs: [
      { label: 'Мощность всасывания', value: '4000 Па' },
      { label: 'Навигация', value: 'Лазерная LDS' },
      { label: 'Время работы', value: 'До 180 минут' },
      { label: 'Площадь уборки', value: 'До 250 м²' },
      { label: 'Уровень шума', value: '65 дБ' },
      { label: 'Подключение', value: 'Wi-Fi 2.4 ГГц / Mi Home' },
      { label: 'Ёмкость бака воды', value: '300 мл' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Максим В.',
        avatar: 'МВ',
        rating: 5,
        date: '25 апреля 2025',
        text: 'Купил месяц назад — не могу представить жизнь без него. Запускаю каждый день пока на работе. Приезжаю домой — чисто. База самоочищающаяся — это важно!',
        helpful: 37,
        verified: true,
      },
      {
        id: 2,
        author: 'Зарина Б.',
        avatar: 'ЗБ',
        rating: 4,
        date: '10 апреля 2025',
        text: 'Карта строится хорошо, ориентируется в квартире отлично. Шерсть кошки собирает полностью. Минус — иногда застревает под диваном.',
        helpful: 19,
        verified: true,
      },
    ],
    tags: ['робот', 'пылесос', 'xiaomi', 'умный дом', 'уборка'],
    deliveryDays: 3,
    warranty: '12 месяцев',
  },

  {
    id: 6,
    slug: 'adidas-ultraboost-23',
    name: 'Adidas Ultraboost 23',
    brand: 'Adidas',
    category: 'Одежда и мода',
    subcategory: 'Кроссовки',
    price: 11990,
    originalPrice: 14990,
    discount: 20,
    currency: 'сом',
    rating: 4.7,
    reviewsCount: 189,
    soldCount: 654,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isExpress: true,
    shortDescription:
      'Беговые кроссовки с подошвой Boost для максимальной отдачи энергии. Верх Primeknit+ адаптируется к форме стопы.',
    description: `Adidas Ultraboost 23 — это эталон беговых кроссовок для городских бегунов. Технология BOOST в подошве содержит тысячи капсул из вспененного TPU, которые сжимаются при ударе и возвращают энергию при отталкивании — это даёт ощущение пружинистости при каждом шаге. Верх Primeknit+ тянется вместе со стопой, обеспечивая второкожую посадку без точек давления. Система Linear Energy Push (LEP) в подошве направляет движение вперёд. Пятка Linear Energy Heel повышает устойчивость. Идеальны как для бега на 5–10 км, так и для ежедневной носки.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600',
        alt: 'Adidas Ultraboost 23 — белые',
        color: '#FFFFFF',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600',
        alt: 'Adidas Ultraboost 23 — подошва',
        color: '#FFFFFF',
      },
    ],
    colors: ['Белый/Золотой', 'Чёрный/Красный', 'Синий/Белый'],
    sizes: ['38', '39', '40', '41', '42', '43', '44', '45', '46'],
    specs: [
      { label: 'Подошва', value: 'BOOST + Continental rubber' },
      { label: 'Верх', value: 'Primeknit+' },
      { label: 'Назначение', value: 'Бег / lifestyle' },
      { label: 'Пронация', value: 'Нейтральная' },
      { label: 'Вес', value: '325 г (размер 42)' },
      { label: 'Дропп', value: '10 мм' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Руслан И.',
        avatar: 'РИ',
        rating: 5,
        date: '14 апреля 2025',
        text: 'Бегаю в них уже 3 месяца по 30 км в неделю. Подошва Boost — лучшее что придумали для бега. Ноги не устают даже после 10 км.',
        helpful: 42,
        verified: true,
      },
      {
        id: 2,
        author: 'Анастасия Г.',
        avatar: 'АГ',
        rating: 5,
        date: '28 марта 2025',
        text: 'Купила для повседневной носки — это лучшие кроссовки для ходьбы. Ноги не болят даже после 15 000 шагов. Выглядят стильно с любой одеждой.',
        helpful: 28,
        verified: true,
      },
    ],
    tags: ['кроссовки', 'adidas', 'boost', 'бег', 'ultraboost'],
    deliveryDays: 2,
    warranty: '30 дней возврат',
  },

  {
    id: 7,
    slug: 'lg-oled-c3-55',
    name: 'LG OLED C3 55" 4K',
    brand: 'LG',
    category: 'Электроника',
    subcategory: 'Телевизоры',
    price: 109990,
    originalPrice: 134990,
    discount: 19,
    currency: 'сом',
    rating: 4.9,
    reviewsCount: 76,
    soldCount: 203,
    inStock: true,
    stockLeft: 2,
    isNew: false,
    isFeatured: true,
    isExpress: false,
    badge: 'Выбор редакции',
    shortDescription:
      'OLED телевизор с процессором α9 AI Gen6, Dolby Vision IQ и совершенными чёрными цветами для кинозала у вас дома.',
    description: `LG OLED C3 — лучший телевизор для домашнего кинотеатра по версии большинства экспертов. Технология OLED обеспечивает абсолютно чёрный цвет (каждый пиксель светится независимо), бесконечный контраст и углы обзора 180°. Процессор α9 AI Gen6 с нейросетевым апскейлингом превращает обычный HD-контент в изображение, близкое к 4K. Поддержка всех HDR-форматов: Dolby Vision IQ, HDR10, HLG. Для геймеров: 4 порта HDMI 2.1 с частотой 120 Гц, VRR, G-Sync и FreeSync Premium. Операционная система webOS 23 с голосовым ассистентом ThinQ AI.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
        alt: 'LG OLED C3 — фронт',
        color: '#1a1a1a',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
        alt: 'LG OLED C3 — в интерьере',
        color: '#1a1a1a',
      },
    ],
    colors: ['Чёрный'],
    specs: [
      { label: 'Экран', value: '55" OLED, 4K 3840×2160' },
      { label: 'Частота', value: '120 Гц (OLED Motion Pro)' },
      { label: 'HDR', value: 'Dolby Vision IQ / HDR10 / HLG' },
      { label: 'Процессор', value: 'α9 AI Gen6' },
      { label: 'Звук', value: '40 Вт, Dolby Atmos' },
      { label: 'HDMI', value: '4 × HDMI 2.1' },
      { label: 'ОС', value: 'webOS 23' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Виктор Н.',
        avatar: 'ВН',
        rating: 5,
        date: '7 мая 2025',
        text: 'После LCD телевизора это просто другой мир. Чёрный цвет реально чёрный, кино смотреть одно удовольствие. Для PS5 — идеальный выбор, 4K 120fps работает.',
        helpful: 53,
        verified: true,
      },
      {
        id: 2,
        author: 'Медина С.',
        avatar: 'МС',
        rating: 5,
        date: '2 апреля 2025',
        text: 'Купили для гостиной. Качество картинки восхитительное. Яркость при дневном свете нормальная. webOS удобная платформа, есть все стриминги.',
        helpful: 31,
        verified: true,
      },
    ],
    tags: ['телевизор', 'oled', 'lg', '4k', 'dolby vision', 'gaming'],
    deliveryDays: 5,
    warranty: '24 месяца',
  },

  {
    id: 8,
    slug: 'nescafe-dolce-gusto-genio',
    name: 'Кофемашина Nescafé Dolce Gusto Genio S Plus',
    brand: 'Nescafé',
    category: 'Дом и сад',
    subcategory: 'Кофемашины',
    price: 7990,
    originalPrice: 9990,
    discount: 20,
    currency: 'сом',
    rating: 4.4,
    reviewsCount: 231,
    soldCount: 876,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isExpress: true,
    shortDescription:
      'Капсульная кофемашина с давлением 15 бар, регулировкой объёма и подключением к смартфону через Bluetooth.',
    description: `Nescafé Dolce Gusto Genio S Plus — идеальная кофемашина для тех, кто ценит качество и удобство. Давление 15 бар извлекает максимум аромата из капсулы, создавая насыщенный эспрессо с густой крема. Технология Fast Heating нагревает воду за 30 секунд. Через приложение Bluetooth можно управлять температурой и объёмом напитка, а также отслеживать количество использованных капсул. Совместима с более чем 50 видами напитков: эспрессо, капучино, латте, чай, горячий шоколад. Съёмный резервуар 1 л удобно наполнять.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
        alt: 'Dolce Gusto Genio — кофемашина',
        color: '#1a1a1a',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600',
        alt: 'Dolce Gusto — кофе',
        color: '#1a1a1a',
      },
    ],
    colors: ['Чёрный', 'Белый', 'Красный'],
    specs: [
      { label: 'Давление', value: '15 бар' },
      { label: 'Резервуар воды', value: '1 л' },
      { label: 'Мощность', value: '1500 Вт' },
      { label: 'Нагрев', value: '30 секунд' },
      { label: 'Управление', value: 'Bluetooth + приложение' },
      { label: 'Вес', value: '2.3 кг' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Ольга К.',
        avatar: 'ОК',
        rating: 5,
        date: '19 апреля 2025',
        text: 'Стоит на работе у нас в офисе. Все довольны! Кофе вкусный, готовится быстро. Капсулы удобно заказывать тут же на Yldam Market.',
        helpful: 44,
        verified: true,
      },
      {
        id: 2,
        author: 'Азамат Д.',
        avatar: 'АД',
        rating: 4,
        date: '5 марта 2025',
        text: 'Хорошая машина за свои деньги. Bluetooth управление — прикольная фича. Минус — капсулы только фирменные и стоят дороговато.',
        helpful: 22,
        verified: true,
      },
    ],
    tags: ['кофемашина', 'капсульная', 'nescafe', 'кофе', 'бытовая техника'],
    deliveryDays: 2,
    warranty: '12 месяцев',
  },

  {
    id: 9,
    slug: 'lego-technic-bugatti',
    name: 'LEGO Technic Bugatti Chiron 42151',
    brand: 'LEGO',
    category: 'Детям',
    subcategory: 'Конструкторы',
    price: 14990,
    originalPrice: 17990,
    discount: 17,
    currency: 'сом',
    rating: 4.8,
    reviewsCount: 58,
    soldCount: 187,
    inStock: true,
    isNew: false,
    isFeatured: false,
    isExpress: false,
    shortDescription:
      'Масштабная модель легендарного суперкара Bugatti Chiron из 905 деталей с подвижными поршнями и открывающимися дверями.',
    description: `LEGO Technic Bugatti Chiron 42151 — захватывающий конструктор для настоящих ценителей автомобилей и инженерии. 905 деталей складываются в детально проработанную модель легендарного суперкара в масштабе 1:8. Откидывающийся капот открывает W16 двигатель с движущимися поршнями. Двери открываются вверх в стиле "крыло чайки". Руль управляет передними колёсами. Коробка передач с двумя скоростями функционирует как настоящая. Готовая модель: 14 см высотой, 47 см длиной, 20 см шириной — настоящий экспонат для полки. Рекомендуется для детей от 10 лет и взрослых.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600',
        alt: 'LEGO Bugatti — вид сбоку',
        color: '#0000FF',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600',
        alt: 'LEGO Bugatti — детали',
        color: '#0000FF',
      },
    ],
    colors: ['Синий/Чёрный'],
    specs: [
      { label: 'Деталей', value: '905 шт.' },
      { label: 'Масштаб', value: '1:8' },
      { label: 'Размер модели', value: '14 × 47 × 20 см' },
      { label: 'Возраст', value: '10+ лет' },
      { label: 'Время сборки', value: '~6–8 часов' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Иван Р.',
        avatar: 'ИР',
        rating: 5,
        date: '22 апреля 2025',
        text: 'Купил сыну на день рождения 12 лет. Собирали вместе 2 вечера — отличное время! Модель выглядит шикарно, стоит на полке как украшение.',
        helpful: 38,
        verified: true,
      },
      {
        id: 2,
        author: 'Адиль М.',
        avatar: 'АМ',
        rating: 5,
        date: '14 марта 2025',
        text: 'Взял для себя — 28 лет, люблю LEGO Technic. Уровень сложности приятный, инструкция понятная. Движущиеся поршни — это просто восторг!',
        helpful: 25,
        verified: true,
      },
    ],
    tags: ['lego', 'конструктор', 'technic', 'bugatti', 'детям', 'коллекция'],
    deliveryDays: 3,
    warranty: '30 дней возврат',
  },

  {
    id: 10,
    slug: 'sony-wh-1000xm5',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    category: 'Электроника',
    subcategory: 'Наушники',
    price: 29990,
    originalPrice: 36990,
    discount: 19,
    currency: 'сом',
    rating: 4.8,
    reviewsCount: 412,
    soldCount: 1567,
    inStock: true,
    isNew: false,
    isFeatured: true,
    isExpress: true,
    badge: 'Выбор экспертов',
    shortDescription:
      'Лучшие полноразмерные наушники с шумоподавлением: 8 микрофонов, 30 часов работы и зарядка 3 минуты = 3 часа.',
    description: `Sony WH-1000XM5 — наушники, которые уже несколько лет подряд признаются лучшими в мире по шумоподавлению. Новый процессор QN2e совместно с процессором V1 обрабатывает сигналы от 8 микрофонов, создавая многоуровневое шумоподавление. Технология Precise Voice Pickup обеспечивает кристально чистые звонки даже в шумных местах. Драйверы 30 мм нового поколения с жёсткой крышкой воспроизводят звук с минимальными искажениями. Поддержка LDAC для передачи Hi-Res Audio через Bluetooth. Адаптивное управление звуком автоматически регулирует настройки в зависимости от вашей активности. Quick Charge: 3 минуты = 3 часа прослушивания.`,
    images: [
      {
        id: 1,
        url: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600',
        alt: 'Sony WH-1000XM5 — чёрные',
        color: '#1a1a1a',
      },
      {
        id: 2,
        url: 'https://images.unsplash.com/photo-1545127398-14699f92334b?w=600',
        alt: 'Sony WH-1000XM5 — белые',
        color: '#F5F5F5',
      },
      {
        id: 3,
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600',
        alt: 'Sony WH-1000XM5 — в использовании',
        color: '#1a1a1a',
      },
    ],
    colors: ['Чёрный', 'Белый (Платиновый серебряный)'],
    specs: [
      { label: 'Тип', value: 'Полноразмерные, закрытые' },
      { label: 'Шумоподавление', value: 'Активное (QN2e + V1)' },
      { label: 'Микрофоны', value: '8 шт. (звонки + ANC)' },
      { label: 'Время работы', value: '30 ч (с ANC) / 40 ч (без)' },
      { label: 'Зарядка', value: 'USB-C, 3 мин = 3 часа' },
      { label: 'Кодеки', value: 'SBC / AAC / LDAC' },
      { label: 'Вес', value: '250 г' },
    ],
    reviews: [
      {
        id: 1,
        author: 'Тимур К.',
        avatar: 'ТК',
        rating: 5,
        date: '1 мая 2025',
        text: 'Пересел с XM4 — разница есть, особенно в ANC и звонках. В самолёте — абсолютная тишина. Звук тёплый и детальный. Комфортно носить весь день.',
        helpful: 76,
        verified: true,
      },
      {
        id: 2,
        author: 'Назгуль Э.',
        avatar: 'НЭ',
        rating: 5,
        date: '20 апреля 2025',
        text: 'Работаю из дома с кошкой и мужем — наконец-то могу сосредоточиться! ANC режим убирает всё. Звук для Spotify — просто превосходный.',
        helpful: 52,
        verified: true,
      },
      {
        id: 3,
        author: 'Борис Л.',
        avatar: 'БЛ',
        rating: 4,
        date: '8 апреля 2025',
        text: 'Наушники отличные, но складываются не так компактно как XM4. Зато лёгче и удобнее на голове. LDAC через Android — слышна разница в качестве.',
        helpful: 29,
        verified: true,
      },
    ],
    tags: ['наушники', 'sony', 'anc', 'ldac', 'hi-res', 'полноразмерные'],
    deliveryDays: 1,
    warranty: '12 месяцев',
  },
];
